---
- name: "fail2ban | Install the required packages in Redhat derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
  block:
    - name: "fail2ban | Update dnf cache"
      ansible.builtin.dnf:
        update_cache: "yes"
    - name: "fail2ban | Install package with dnf"
      ansible.builtin.dnf:
        name: "{{ hostvars[inventory_hostname]['fail2ban_package'] }}"
        state: "{{ vars['fail2ban_package_state'] | default(omit) }}"
- name: "fail2ban | Install the required packages in Debian derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
  block:
    - name: "fail2ban | Update apt cache"
      ansible.builtin.apt:
        update_cache: "yes"
    - name: "fail2ban | Install package with apt"
      ansible.builtin.apt:
        name: "{{ hostvars[inventory_hostname]['fail2ban_package'] }}"
        state: "{{ vars['fail2ban_package_state'] | default(omit) }}"
- name: "fail2ban | Install the required packages in ArchLinux derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Archlinux'"
  block:
    - name: "fail2ban | Update pacman cache"
      community.general.pacman:
        update_cache: "yes"
    - name: "fail2ban | Install package with pacman"
      community.general.pacman:
        name: "{{ hostvars[inventory_hostname]['fail2ban_package'] }}"
        state: "{{ vars['fail2ban_package_state'] | default(omit) }}"
