---
- name: "Restart fail2ban"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['fail2ban_service'] }}"
    daemon_reload: "yes"
    state: "restarted"
  when:
    - "hostvars[inventory_hostname]['fail2ban'] is defined"
    - "hostvars[inventory_hostname]['fail2ban'] != ''"
    - "hostvars[inventory_hostname]['fail2ban'] |
       json_query(vars['fail2ban_restart']) is defined"
    - "hostvars[inventory_hostname]['fail2ban'] |
       json_query(vars['fail2ban_restart']) == 'true'"
  vars:
    fail2ban_restart: "[] | map(&restart || 'false', @) | [0]"
